apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-external-secrets
  namespace: vault-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secret-store # name of the secret store
    kind: ClusterSecretStore
  target:
    name: sample-k8s-secret-created-by-external-secrets # Name of K8s secret object
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: secret/sample-application-secrets # Path in Vault
