apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store

spec:
  provider:
    vault:
      server: "https://vault.vault-operator:8200"
      caProvider:
        name: vault-tls
        namespace: vault-operator
        type: Secret
        key: ca.crt
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "k8s-one"
          role: "k8s-one-external-secrets-role"
