apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store

spec:
  provider:
    vault:
      server: "https://vault.vault-operator:8200"
      # adding this to verify CA, as we are using self-signed certificates.
      caProvider:
        name: vault-tls
        namespace: vault-operator
        type: Secret
        key: ca.crt
      path: "secret" #! Path for your secret engine in Vault.
      version: "v2"
      auth:
        kubernetes:
          mountPath: "k8s-one" #! name of the kubernetes auth
          role: "k8s-one-external-secrets-role" #! role for kubernetes auth
